### PR TITLE
Fix transcription of `unque` in the classical mode

### PR DESCRIPTION
**Pull request by kriskowal**

### CODE REVIEW

**Comment by kriskowal** [comment]
To verify this change, scroll up and click on the "Preview" link posted by the Vercel deployment bot. Then, on the test deployment, click "Select Mode", then select Classical mode, either as specifically attested by Namarie, or a custom variant. Then type "unque" or similar Quenya words with the "nq[u]" cluster and verify the resulting transcription.

**Review by arnog — APPROVED** [review]
Looks good.
In general, in Quenya mode, "QU" should be handled as "Q"

**Comment by dreamingfifi** [comment]
Looks good!

**Review by dreamingfifi — APPROVED** [review]

**Comment by kriskowal** [comment]
> Looks good.
> In general, in Quenya mode, "QU" should be handled as "Q"

Thank you. The treatment of Q[U] without the prefix N is captured here:

https://github.com/kriskowal/tengwarjs/pull/64/files#diff-158d7d7deaf2f3917f94dc535c28d021ae530f5312795bdf614025fa6cbae360R275-R282

It seems I neglected the pre-nasal, but this should fix it generally.

The treatment here and there is to recognize both Q and QU as equivalent, and replaying the second letter if not U to the next parser state.

**Pull request merged**
